service: personal-backend

plugins:
  - serverless-wsgi
  - serverless-apigw-binary
  - serverless-dotenv-plugin
  
useDotenv: true

provider:
  stage: ${opt:stage,'dev'} 
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30
  environment:
  ecr: 
    images:
      personal-img: 
        path: ./
        platform: linux/amd64

custom:  
  wsgi:
    app: app.app
    packRequirements: false

  apigwBinary:
    types:
      - 'multipart/form-data'

  dotenv:
    basePath: ./
    include:
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - MASTER_USER
      - MASTER_PASSWORD
      - ADMIN_ACCESS_KEY_ID
      - ADMIN_SECRET_ACCESS_KEY

functions:
  app:
    image:
      name: personal-img
      command: 
        - app.handler
    events:
      - http: 
          method: ANY
          path: /{proxy+}
          cors:
            origin: '*'
            headers: '*'